### ISSUE TITLE
[BUG] group not found error when patching

### ISSUE THREAD

**Issue by tomchiverton** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#87]
**Describe the bug**
Error when applying patch - group not found

**To Reproduce**
```
tchiverton@noctua:~/Downloads$ ./Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.8.elf
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1705, in __call__
  File "Builder.py", line 1129, in patchInstall
  File "Builder.py", line 1049, in copyRFunctions
  File "Builder.py", line 356, in fullPatcher
  File "shutil.py", line 1050, in chown                                                                                           
LookupError: no such group: 'tchiverton'     
```

**Expected behavior**
Patched.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 80.0.1

**Additional information**
Manually adding a group with the same name as my user fixed it.

**Comment by Izheil** [comment]
Should be fixed now on [1.7.8-rev2](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/download/FF81/Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.8-rev2.elf)
